name: flutter_bluetooth_serial
version: 1.0.0
description: A basic Flutter Bluetooth Serial library
authors: 
- Eduardo Folly <edufolly@gmail.com>
- Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial
repository: https://github.com/edufolly/flutter_bluetooth_serial
issue_tracker: https://github.com/edufolly/flutter_bluetooth_serial/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.github.edufolly.flutterbluetoothserial
    pluginClass: FlutterBluetoothSerialPlugin


